Hw 04 ts
HennadiiMariiev/nodejs-homework-rest-api pull request #4
Opened 2021-11-14 10:45 UTC by HennadiiMariiev

- [x] **task1:** create model and schema for user
- [x] **task2:** add signup and login routes
- [x] **task3:** add token middleware
- [x] **task4:** add logout route
- [x] **task5:** add currentUser route
- [x] **ADDITIONAL:**
  - [x] **add pagination**, but without library, because the last one returns lots of errors in typescript after adding @typescript/types
  - [x]  **add filtering**
  - [x]  **add subscription**

2021-11-16 15:47 UTC, TViglesGoom requested changes

2021-11-16 15:47 UTC, TViglesGoom commented on src/services/contacts.service.ts
> +      }).populate("owner", "email");
А если одновременно пагинация и фильтрация?

2021-11-16 15:47 UTC, TViglesGoom commented on src/services/contacts.service.ts
> +    }
В миддлвар валидацию данных

2021-11-16 15:47 UTC, TViglesGoom commented on src/services/contacts.service.ts
> +      return new BadRequest("Contact with same email or phone already exists.");
Может, "не существует"?

2021-11-16 15:47 UTC, TViglesGoom commented on src/services/contacts.service.ts
> +
В миддлвар

2021-11-16 15:47 UTC, TViglesGoom commented on src/services/contacts.service.ts
> +    }
В миддлвар

2021-11-16 15:47 UTC, TViglesGoom commented on src/helpers/service.helpers.ts
> +  if (
во первых уберите отсюда if, вместо него поставьте return, а нижние ретёрны уберите

2021-11-16 15:47 UTC, TViglesGoom commented on src/helpers/service.helpers.ts
> +    (req.query.favorite === "true" || req.query.favorite === "false")
тут достаточно будет `["true", "false"].includes(req.query.favourite)`

2021-11-16 15:47 UTC, TViglesGoom commented on src/helpers/service.helpers.ts
> +    }
А если эта проверка не пройдёт? Вы undefined возвращаете? Вы же используете тайпскрипт. Прописали бы, что ваша функция булин возвращает. Оно бы вам подсветило.

2021-11-16 15:47 UTC, TViglesGoom commented on src/helpers/controller.helpers.ts
> +  if (checkObject instanceof Error || !checkObject) {
Не совсем понимаю, а с какой целью тут нужен !checkObject? И снова, уберите нижные ретёрны, вместо if поставьте return

2021-11-16 15:47 UTC, TViglesGoom commented on src/config/constants.ts
> +export const DB_URL = process.env.DB_URL!;
А почему такой нейминг переменных окружения? Для чего "!"? И почему вы не используете деструктуризацию?

2021-11-16 15:47 UTC, TViglesGoom commented on src/config/index.ts
> +import { PORT, DB_URL, DB_NAME, SALT_COUNT, SECRET_KEY } from "./constants";
да вот нет. Как "ПЕРЕМЕННАЯ окружения" может быть "КОНСТАНТОЙ". Это дело нейминга, конечно, но очень контринтуитивно.

2021-11-16 19:37 UTC, HennadiiMariiev commented on src/helpers/service.helpers.ts
> +    }
Эта функция и возвращает false, если проверка не условия не выполняются.
Там на 23 строке return. Тайпскрипт сам и подсвечивает возврат булеан.
Я понял, что нужно дописать возвращаемое значение.

2021-11-16 20:15 UTC, HennadiiMariiev commented on src/services/contacts.service.ts
> +      return new BadRequest("Contact with same email or phone already exists.");
Проверка на дубликат контакта (поля почты и телефона). Тут как раз именно "существует" имеется ввиду. Что такие уже в базе есть.

2021-11-16 20:16 UTC, HennadiiMariiev commented on src/helpers/service.helpers.ts
> +    (req.query.favorite === "true" || req.query.favorite === "false")
О, вот это красиво) спасибо!

2021-11-16 20:21 UTC, HennadiiMariiev commented on src/helpers/controller.helpers.ts
> +  if (checkObject instanceof Error || !checkObject) {
Проверка что приходящий объект null.
Теперь понял, что эта проверка избыточна... Все еще от чистого ДжЕса не переключился на ТайпСкрипт.

2021-11-17 08:45 UTC, HennadiiMariiev commented on src/services/contacts.service.ts
> +      }).populate("owner", "email");
Как раз думал про этот кейс)
Конечно, нужно было это предвидеть)))

2021-11-17 08:49 UTC, HennadiiMariiev commented on src/config/index.ts
> +import { PORT, DB_URL, DB_NAME, SALT_COUNT, SECRET_KEY } from "./constants";
ок) переименовал.
Дело в нейминге, это действительно конфигурация. Называть константами действительно не очень... Хоть по сути переменные енвы являются константами.

СПАСИБО за правочки!
Набираюсь с ними опыта понемногу)

2021-11-18 09:26 UTC, TViglesGoom approved these changes

2021-11-21 17:42 UTC, merged