Hw 05 ts
HennadiiMariiev/nodejs-homework-rest-api pull request #5
Opened 2021-11-21 17:47 UTC by HennadiiMariiev

- [x] **task1:** create _public_ folder and _avatars_ subfolder for static
- [x] **task2:** add _avatarURL_ field in user schema
- [x] **task3:** add avatar creation with  _gravatar_
- [x] **task4:** add logout route
- [x] **task5:** add PATCH route for updating avatar
- [ ] **ADDITIONAL:**
  - [ ] auth unit-tests
  - [ ] e2e tests for avatars

2021-11-21 22:12 UTC, KirillKulakow commented on src/services/users.service.ts
> +    const avatarURL = gravatar.url(email);
как по мне ответ по данной ссылке не сильно корректен - думаю что нужно добавить одну из опций для того чтобы url был валидным

2021-11-21 22:14 UTC, KirillKulakow commented on src/services/users.service.ts
> +    return error;
думаю что unlink нужно добавить и в catch

2021-11-21 22:15 UTC, KirillKulakow commented on temp/os.js
> +const os = require('os');
это тебе зачем?

2021-11-21 22:16 UTC, KirillKulakow requested changes
need some fix

2021-11-22 07:45 UTC, HennadiiMariiev commented on temp/os.js
> +const os = require('os');
Это тестировал невалидные mime-types. Закинул то что было под рукой (главное, с другим расширением)))

2021-11-22 07:45 UTC, HennadiiMariiev commented on src/services/users.service.ts
> +    const avatarURL = gravatar.url(email);
Да, понял)
url был без протокола. Пофиксил)

2021-11-22 19:35 UTC, KirillKulakow approved these changes

2021-11-24 18:27 UTC, merged